// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpW_-hAyqNX8VkhOJIGXW4v3gHG5M6BLw',
    appId: '1:394426434833:web:c283b22de9ae32eb4938b0',
    messagingSenderId: '394426434833',
    projectId: 'book-my-coolie',
    authDomain: 'book-my-coolie.firebaseapp.com',
    storageBucket: 'book-my-coolie.appspot.com',
    measurementId: 'G-86ET0H0GNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDp03gdJJUd05cNkiQUSO17LiFcVZBVg',
    appId: '1:394426434833:android:9527dda65dcfde304938b0',
    messagingSenderId: '394426434833',
    projectId: 'book-my-coolie',
    storageBucket: 'book-my-coolie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqbO9-EwuKwnk2kK9MUL8_CRh1ZBEyPs',
    appId: '1:394426434833:ios:efd5d5df8e44be7b4938b0',
    messagingSenderId: '394426434833',
    projectId: 'book-my-coolie',
    storageBucket: 'book-my-coolie.appspot.com',
    androidClientId:
        '394426434833-7v3gaur9rcf95tkrd9lu3c1kfnspfedp.apps.googleusercontent.com',
    iosClientId:
        '394426434833-hbs90fdrrp6a9jq9e4qsm8m0u56qp9fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqbO9-EwuKwnk2kK9MUL8_CRh1ZBEyPs',
    appId: '1:394426434833:ios:efd5d5df8e44be7b4938b0',
    messagingSenderId: '394426434833',
    projectId: 'book-my-coolie',
    storageBucket: 'book-my-coolie.appspot.com',
    androidClientId:
        '394426434833-7v3gaur9rcf95tkrd9lu3c1kfnspfedp.apps.googleusercontent.com',
    iosClientId:
        '394426434833-hbs90fdrrp6a9jq9e4qsm8m0u56qp9fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolie',
  );
}
